//LOS LEDS TIENEN DOS MODOS DE TRABAJO, UNO DIGITAL (PIN DIGITAL) Y EL OTRO ANALOGICO (PIN PWM)

int led = 13; //ARDUINO UNO /MEGA CUENTAN CON UN LED EN LA PLACA QUE SIRVE PARA REALIZAR PRUEBAS
// ESTE LED SE UBICA EN EL PIN 13 

void setup(){

  //SIEMPRE QUE SE TRABAJE CON UN PIN DIGITAL, SE DEBE DEFINIR SI EL PIN SERA DE ENTRADA O DE SALIDA

  pinMode(led, OUTPUT);
}

void loop(){ //16MhZ

    ///OP1

  digitalWrite(led, HIGH);
  
  delay(1000);

  digitalWrite(led, LOW);

   ///OP2. -- lo más comun es esto
   delay(1000);

}


